version: '3.9'
services:
  guitar-shop.postgres:
    image: postgres:14-alpine
    container_name: guitar-shop.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - guitar-shop.postgres:/var/lib/postgresql/data

    networks:
      - guitar-shop

  guitar-shop.pgadmin:
    image: dpage/pgadmin4
    container_name: guitar-shop.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    depends_on:
      - guitar-shop.postgres
    networks:
      - guitar-shop

volumes:
  guitar-shop.postgres:


networks:
  guitar-shop:
    driver: bridge
