version: '3.9'
services:
  guitar-shop.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    container_name: "guitar-shop.notify.fakesmtp"
    hostname: "guitar-shop.notify.fakesmtp"
    ports:
      - "8025:8025"
      - "1085:8080"